/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShoppingListIdRouteImport } from './routes/shopping_.$listId'

const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListIdRoute = ShoppingListIdRouteImport.update({
  id: '/shopping_/$listId',
  path: '/shopping/$listId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shopping': typeof ShoppingRoute
  '/shopping/$listId': typeof ShoppingListIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shopping': typeof ShoppingRoute
  '/shopping/$listId': typeof ShoppingListIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shopping': typeof ShoppingRoute
  '/shopping_/$listId': typeof ShoppingListIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shopping' | '/shopping/$listId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shopping' | '/shopping/$listId'
  id: '__root__' | '/' | '/shopping' | '/shopping_/$listId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShoppingRoute: typeof ShoppingRoute
  ShoppingListIdRoute: typeof ShoppingListIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping_/$listId': {
      id: '/shopping_/$listId'
      path: '/shopping/$listId'
      fullPath: '/shopping/$listId'
      preLoaderRoute: typeof ShoppingListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShoppingRoute: ShoppingRoute,
  ShoppingListIdRoute: ShoppingListIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
